In [1]:
import pandas as pd
import os
from pathlib import Path
from datetime import datetime

In [2]:
file_path = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/raw/crop_yields.csv"

In [3]:
# In order for this shortcut filepath to work I had to allow full disk access to the terminal (since that's how I was launching jupyter notebook)
crop_data = pd.read_csv(file_path)

In [4]:
# Filter down to just PT
pt_data = crop_data[crop_data['country'] == "Portugal"]

In [5]:
columns_to_drop = [col for col in pt_data.columns if col.endswith("_attainable_yield") or col.endswith("_yield_gap")]
pt_filtered = pt_data.drop(columns=columns_to_drop)

In [6]:
columns_any_non_na = pt_filtered.columns[pt_filtered.notna().any()].tolist()

In [7]:
# columns_any_non_na

In [8]:
pt_filtered.head()

,country,year,abaca__manila_hemp__raw_yield,agave_fibres__raw__n_e_c__yield,almond_yield,apples_yield,apricots_yield,areca_nuts_yield,artichokes_yield,asparagus_yield,...,true_hemp__raw_or_retted_yield,tung_nuts_yield,vanilla__raw_yield,vegetables_yield,vetches_yield,walnuts_yield,watermelons_yield,wheat_yield,yams_yield,yautia_yield
10422,Portugal,1961,NaN,NaN,0.4324,4.6667,8.296,NaN,NaN,NaN,...,1.0000,NaN,NaN,16.479300,NaN,2.6923,5.5000,0.6515,7.8947,NaN
10423,Portugal,1962,NaN,NaN,0.4737,3.8667,6.840,NaN,NaN,NaN,...,1.1316,NaN,NaN,16.337100,NaN,2.5000,5.5000,0.8857,7.8947,NaN
10424,Portugal,1963,NaN,NaN,0.3333,5.1111,5.660,NaN,NaN,NaN,...,1.0000,NaN,NaN,18.670500,NaN,2.3214,5.6667,0.8002,7.8947,NaN
10425,Portugal,1964,NaN,NaN,0.3611,5.0000,4.430,NaN,NaN,NaN,...,1.3072,NaN,NaN,19.978899,NaN,2.3214,5.4839,0.6887,8.0952,NaN
10426,Portugal,1965,NaN,NaN,0.3684,5.3333,7.760,NaN,NaN,NaN,...,1.1913,NaN,NaN,21.141200,NaN,2.3214,5.6452,0.9750,8.0000,NaN

In [9]:
df_cleaned = pt_filtered.dropna(axis=1, how='all')

In [84]:
# Show the max number of columns possible
pd.set_option('display.max_columns', None)
# Yields are measured in tonnes per hectare
df_cleaned.head(50)

,country,year,almond_yield,apples_yield,apricots_yield,asparagus_yield,avocados_yield,banana_yield,barley_yield,bean_yield,beans__green_yield,blueberries_yield,broad_beans_and_horse_beans__green_yield,broad_beans_yield,cabbages_yield,carrots_and_turnips_yield,cauliflowers_and_broccoli_yield,cereals_n_e_c__yield,cereal_yield,cherries_yield,chestnut_yield,chickpeas_yield,chillies_and_peppers__green__capsicum_spp__and_pimenta_spp__yield,citrus_fruit_yield,cucumbers_and_gherkins_yield,currants_yield,eggplants_yield,fibre_crops__fibre_equivalent_yield,figs_yield,flax__raw_or_retted_yield,fruit_yield,garlic_yield,grapefruit_yield,grapes_yield,groundnut_yield,hazelnuts_yield,hempseed_yield,hop_cones_yield,kiwi_yield,leeks_yield,lemons_and_limes_yield,lettuce_yield,linseed_yield,locust_beans__carobs__yield,lupins_yield,maize_yield,melon_yield,millet_yield,oats_yield,oilcrops__cake_equivalent_yield,oilcrops__oil_equivalent_yield,olives_yield,onions_and_shallots__green_yield,onions_yield,orange_yield,other_berries_and_fruits_of_the_genus_vaccinium_n_e_c__yield,other_fruits__n_e_c__yield,other_nuts__excluding_wild_edible_nuts_and_groundnuts__in_shell__n_e_c__yield,other_pome_fruits_yield,other_pulses_n_e_c__yield,other_stone_fruits_yield,other_vegetables__fresh_n_e_c__yield,peaches_and_nectarines_yield,pears_yield,peas__green_yield,pineapples_yield,plums_yield,potato_yield,pulses_yield,pumpkins__squash_and_gourds_yield,quinces_yield,raspberries_yield,rice_yield,roots_and_tubers_yield,rye_yield,safflower_seed_yield,sour_cherries_yield,spinach_yield,strawberries_yield,sugarbeet_yield,sugarcane_yield,sugar_crops_yield,sunflower_yield,sweet_potatoes_yield,tangerines_yield,tea_yield,tobacco_yield,tomato_yield,treenuts_yield,triticale_yield,true_hemp__raw_or_retted_yield,vegetables_yield,walnuts_yield,watermelons_yield,wheat_yield,yams_yield
10422,Portugal,1961,0.4324,4.666700,8.2960,NaN,NaN,32.190500,0.4106,0.1598,10.000000,NaN,10.0000,0.3657,16.666700,31.818200,NaN,NaN,0.7848,10.571400,2.0000,0.3717,2.941200,8.508100,NaN,NaN,NaN,0.9695,0.9000,0.955720,3.1753,6.0000,5.0000,4.7244,NaN,1.2500,0.2459,NaN,NaN,NaN,7.692300,20.000000,0.2952,NaN,0.7925,1.277900,13.200000,1.7738,0.2422,13.9183,492.30328,NaN,NaN,19.555600,8.733300,NaN,3.32,0.7050,NaN,0.6250,2.5000,15.002899,8.990700,9.090899,NaN,7.5000,16.503600,9.753500,0.2175,15.000000,5.0,NaN,4.6781,9.592100,0.3995,NaN,3.1950,NaN,1.650000,36.5200,38.4615,36.920600,NaN,7.1429,7.700000,0.6400,2.5000,23.920000,1.2880,NaN,1.0000,16.479300,2.6923,5.500000,0.6515,7.8947
10423,Portugal,1962,0.4737,3.866700,6.8400,NaN,NaN,28.977299,0.5362,0.1352,10.000000,NaN,10.0000,0.5276,16.666700,36.363598,NaN,NaN,0.8806,11.178599,2.0000,0.3086,2.941200,9.613999,NaN,NaN,NaN,0.9247,0.9367,0.809524,4.7495,6.0000,7.4074,8.7125,NaN,1.2500,0.2632,NaN,NaN,NaN,10.000000,21.000000,0.2564,NaN,0.8070,1.175100,13.578899,1.7260,0.3603,12.8708,197.96260,NaN,NaN,18.600000,10.064500,NaN,3.36,0.7080,NaN,0.6875,2.5000,13.275600,7.200000,9.545500,NaN,7.5000,7.478300,8.779900,0.2114,15.000000,5.0,NaN,4.7346,8.673099,0.5546,NaN,2.8571,NaN,1.657900,32.6087,38.4615,34.722200,NaN,7.1429,6.150000,0.5556,2.5000,31.743198,1.3451,NaN,1.1316,16.337100,2.5000,5.500000,0.8857,7.8947
10424,Portugal,1963,0.3333,5.111100,5.6600,NaN,NaN,30.108700,0.4852,0.1412,10.000000,NaN,10.0000,0.5329,17.021300,30.000000,NaN,NaN,0.8286,10.551700,1.9394,0.3740,2.941200,6.679400,NaN,NaN,NaN,0.8460,1.0767,0.781481,4.2785,6.0000,7.4074,7.2939,NaN,1.4000,0.2655,NaN,NaN,NaN,7.692300,20.000000,0.2593,NaN,0.8017,1.072900,13.636399,1.7241,0.3342,15.8319,461.70160,NaN,NaN,21.199999,6.866700,NaN,3.40,0.7125,NaN,0.6875,2.5000,16.000000,8.828600,11.599999,NaN,7.8125,12.160000,10.723100,0.2283,15.000000,5.0,NaN,4.5518,10.496300,0.6775,NaN,2.8571,NaN,1.925000,36.0000,37.5000,36.486500,NaN,7.3333,4.277800,0.6000,2.4889,33.939000,1.1390,NaN,1.0000,18.670500,2.3214,5.666700,0.8002,7.8947
10425,Portugal,1964,0.3611,5.000000,4.4300,NaN,NaN,31.844700,0.4121,0.1510,10.000000,NaN,10.0000,0.4711,16.981100,30.555600,NaN,NaN,0.8143,11.965500,2.1951,0.3241,2.941200,8.679999,NaN,NaN,NaN,0.9794,1.2200,0.778598,4.4961,6.0000,7.4074,7.4960,NaN,1.4545,0.2410,NaN,NaN,NaN,7.692300,20.000000,0.3395,NaN,0.8000,1.202700,13.318200,1.7256,0.2790,13.9221,162.52130,NaN,NaN,18.975000,9.312500,NaN,3.44,0.7170,NaN,0.7500,2.5000,17.002499,5.000000,10.666699,NaN,7.8125,9.458300,10.468699,0.2137,15.000000,5.0,NaN,4.7991,10.306100,0.5358,NaN,2.8571,NaN,2.575000,32.6087,37.5000,34.285698,NaN,8.0000,4.210500,0.6000,2.0000,33.782600,1.3568,NaN,1.3072,19.978899,2.3214,5.483900,0.6887,8.0952
10426,Portugal,1965,0.3684,5.333300,7.7600,NaN,NaN,32.075500,0.5735,0.1243,10.000000,NaN,10.0000,0.3780,16.964300,30.952398,NaN,NaN,0.8557,12.599999,1.0682,0.2069,2.941200,9.095400,NaN,NaN,NaN,0.9378,1.0667,0.836237,4.7629,6.0000,7.4074,8.0760,NaN,1.6667,0.2609,NaN,NaN,NaN,8.750000,20.000000,0.3659,NaN,0.7000,0.948300,13.461499,1.7204,0.3649,16.6310,320.25860,NaN,NaN,19.047600,9.625000,NaN,3.48,0.7215,NaN,0.6875,2.5000,16.998999,7.408200,12.400000,NaN,7.7651,8.916699,8.778100,0.1747,15.000000,5.0,NaN,3.8688,8.728600,0.6610,NaN,2.8571,NaN,2.500000,39.0000,37.5000,38.513500,NaN,8.1250,5.702300,0.6000,2.1765,33.142900,0.8003,NaN,1.1913,21.141200,2.3214,5.645200,0.9750,8.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10479,Portugal,2018,0.5459,18.104300,6.2679,9.333300,NaN,21.571400,3.0365,NaN,13.973000,5.7306,10.0152,0.7303,26.808100,53.238400,13.684000,1.5500,4.8090,2.874600,0.8781,0.7710,41.010800,18.928799,71.000000,2.1667,62.272697,NaN,0.9056,NaN,7.4745,12.0000,12.0000,4.4864,NaN,0.6857,NaN,2.0,12.430699,26.977499,15.373799,23.231200,NaN,NaN,NaN,8.563600,34.664898,NaN,1.5462,NaN,NaN,2.0448,NaN,35.352898,19.508900,10.153800,NaN,NaN,7.0292,0.7709,4.3333,14.420000,11.395699,12.908000,7.8263,NaN,9.711100,20.754300,0.7635,28.012000,NaN,19.235699,5.4784,20.754300,1.0971,NaN,1.6667,15.795500,33.218800,NaN,NaN,NaN,1.6881,NaN,16.462200,NaN,2.2500,84.002495,0.4278,1.7845,NaN,48.512300,1.2338,27.956999,2.5938,NaN
10480,Portugal,2019,0.6545,25.905699,6.6852,9.666699,6.752500,24.196400,3.2657,NaN,13.083300,6.1129,7.8103,0.6677,25.671500,51.566300,13.367200,1.4068,5.1765,3.442900,0.8481,0.9671,43.129400,19.282200,69.133300,1.9167,70.750000,NaN,1.2100,NaN,8.3523,5.8571,11.0000,4.9237,NaN,0.6875,NaN,NaN,12.938399,29.068499,14.314799,24.079100,NaN,NaN,NaN,9.804299,23.113300,NaN,1.4092,NaN,NaN,2.4818,NaN,38.714300,20.228300,14.650000,NaN,NaN,7.0758,0.9682,3.1250,30.333300,11.841300,17.517200,7.9613,NaN,11.366099,23.584799,1.1918,26.866900,NaN,18.636400,5.6018,23.584799,1.1508,NaN,2.0000,14.200000,22.309100,NaN,NaN,NaN,1.5451,NaN,16.207699,NaN,NaN,96.293900,0.4199,1.6490,NaN,53.280900,1.1471,25.188900,2.7014,NaN
10481,Portugal,2020,0.6039,19.991600,6.2308,6.444400,7.076900,23.482100,3.2571,NaN,13.483900,6.1928,9.2647,0.7028,28.982698,51.172398,14.427500,1.3051,4.8813,1.446000,0.8159,0.9860,42.578100,19.689900,63.090897,1.9167,72.222200,NaN,1.1575,NaN,7.8051,18.2836,11.0000,4.8579,NaN,0.6563,NaN,2.0,13.242800,28.021900,15.365900,25.403200,NaN,NaN,NaN,9.344999,31.608300,NaN,1.3048,NaN,NaN,1.9308,NaN,36.035500,20.631800,14.250000,NaN,NaN,6.6842,0.9862,3.1250,15.777800,9.174100,11.562200,6.7735,NaN,10.480900,23.367899,1.1858,26.453900,NaN,18.476599,5.1191,23.367899,1.2369,NaN,1.8000,8.979800,29.074099,NaN,NaN,NaN,1.5047,NaN,16.246199,NaN,NaN,93.032600,0.3918,1.6921,NaN,46.506200,0.9463,40.852898,2.7704,NaN
10482,Portugal,2021,0.7098,26.453299,6.5094,2.357100,7.848200,22.312500,3.0024,NaN,15.626499,6.6178,8.7463,0.7002,28.703499,53.973198,15.495199,1.2542,5.3797,3.792400,0.7489,0.9757,44.056900,20.053000,70.350000,2.2500,63.500000,NaN,1.3263,NaN,9.1907,14.8125,11.0000,5.5670,NaN,0.5854,NaN,NaN,15.982699,23.922499,16.281399,28.018599,NaN,NaN,NaN,10.104600,28.212900,NaN,1.2553,NaN,NaN,3.6165,NaN,33.323200,21.096800,14.549999,NaN,NaN,6.8921,0.9756,3.2500,17.500000,11.204800,20.193499,6.0880,NaN,12.771399,24.602400,1.1515,27.364698,NaN,19.275900,5.9911,24.602400,1.1818,NaN,2.3000,18.114899,37.721300,NaN,NaN,NaN,1.6834,NaN,15.846700,NaN,NaN,97.937000,0.4276,1.5180,NaN,50.611700,1.3440,41.493298,2.4229,NaN
10483,Portugal,2022,0.7235,21.208300,6.6833,1.250000,8.084599,24.534500,2.3286,NaN,13.135900,7.2710,4.3529,0.5218,28.739500,48.572800,12.812699,0.9492,5.1371,3.929900,0.5879,0.8242,38.943398,20.770800,65.631600,2.0909,59.888897,NaN,0.8674,NaN,8.2291,10.8772,11.0000,5.1397,NaN,0.7636,NaN,NaN,15.034100,26.026999,18.226200,24.530200,NaN,NaN,NaN,9.619400,29.914598,NaN,0.9513,NaN,NaN,2.0857,NaN,38.563297,21.990099,15.055599,NaN,NaN,6.4762,0.8626,3.4000,13.299999,8.571800,12.191700,4.1392,NaN,10.835400,22.042000,0.9984,23.910700,NaN,18.903200,5.7069,22.042000,0.9833,NaN,1.9000,12.599999,34.788498,NaN,NaN,NaN,1.5671,NaN,14.996500,NaN,NaN,84.817900,0.4091,1.1908,NaN,45.930000,1.2987,33.275898,1.9942,NaN

In [16]:
# Write to .csv
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_crop_yield_cleaned.csv"
df_cleaned.to_csv(file_name, sep=',', encoding='utf-8')

In [67]:
# Convert from wide to long format
melted_df = df_cleaned.melt(id_vars=['country', 'year'], var_name='crop', value_name='yield')

In [80]:
# filtered_df = melted_df[melted_df['crop'] == 'avocado']
# filtered_df

In [85]:
melted_df = melted_df.dropna()
melted_df['crop'].unique()
filtered_df = melted_df[melted_df['crop'] == 'avocados']
filtered_df.head(100)

      country  year      crop     yield
277  Portugal  1990  avocados  1.901800
278  Portugal  1991  avocados  1.812500
279  Portugal  1992  avocados  1.813100
280  Portugal  1993  avocados  1.537700
281  Portugal  1994  avocados  1.274500
306  Portugal  2019  avocados  6.752500
307  Portugal  2020  avocados  7.076900
308  Portugal  2021  avocados  7.848200
309  Portugal  2022  avocados  8.084599

In [69]:
melted_df['crop'] = melted_df['crop'].str.replace('_yield', '')

In [86]:
# Write to .csv
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_crop_data_long.csv"
melted_df.to_csv(file_name, sep=',', encoding='utf-8')

In [65]:
top_20_crops = melted_df.sort_values(['year', 'yield'], ascending=[True, False]) \
                        .groupby('year') \
                        .head(20) \
                        .sort_values('year')

In [26]:
# Write to .csv
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_top_20_crops_by_year.csv"
top_20_crops.to_csv(file_name, sep=',', encoding='utf-8')