In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
file_path = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/raw/crop_yields.csv"

In [3]:
# In order for this shortcut filepath to work I had to allow full disk access to the terminal (since that's how I was launching jupyter notebook)
crop_data = pd.read_csv(file_path)

In [4]:
# Filter down to just PT
pt_data = crop_data[crop_data['country'] == "Portugal"]

In [5]:
columns_to_drop = [col for col in pt_data.columns if col.endswith("_attainable_yield") or col.endswith("_yield_gap")]
pt_filtered = pt_data.drop(columns=columns_to_drop)

In [6]:
columns_any_non_na = pt_filtered.columns[pt_filtered.notna().any()].tolist()

In [7]:
# columns_any_non_na

In [8]:
pt_filtered.head()

,country,year,abaca__manila_hemp__raw_yield,agave_fibres__raw__n_e_c__yield,almond_yield,apples_yield,apricots_yield,areca_nuts_yield,artichokes_yield,asparagus_yield,...,true_hemp__raw_or_retted_yield,tung_nuts_yield,vanilla__raw_yield,vegetables_yield,vetches_yield,walnuts_yield,watermelons_yield,wheat_yield,yams_yield,yautia_yield
10422,Portugal,1961,NaN,NaN,0.4324,4.6667,8.296,NaN,NaN,NaN,...,1.0000,NaN,NaN,16.479300,NaN,2.6923,5.5000,0.6515,7.8947,NaN
10423,Portugal,1962,NaN,NaN,0.4737,3.8667,6.840,NaN,NaN,NaN,...,1.1316,NaN,NaN,16.337100,NaN,2.5000,5.5000,0.8857,7.8947,NaN
10424,Portugal,1963,NaN,NaN,0.3333,5.1111,5.660,NaN,NaN,NaN,...,1.0000,NaN,NaN,18.670500,NaN,2.3214,5.6667,0.8002,7.8947,NaN
10425,Portugal,1964,NaN,NaN,0.3611,5.0000,4.430,NaN,NaN,NaN,...,1.3072,NaN,NaN,19.978899,NaN,2.3214,5.4839,0.6887,8.0952,NaN
10426,Portugal,1965,NaN,NaN,0.3684,5.3333,7.760,NaN,NaN,NaN,...,1.1913,NaN,NaN,21.141200,NaN,2.3214,5.6452,0.9750,8.0000,NaN

In [39]:
df_cleaned = pt_filtered.dropna(axis=1, how='all')

In [44]:
pd.set_option('display.max_columns', None)
# Yields are measured in tonnes per hectare
df_cleaned.head()

,country,year,almond_yield,apples_yield,apricots_yield,asparagus_yield,avocados_yield,banana_yield,barley_yield,bean_yield,beans__green_yield,blueberries_yield,broad_beans_and_horse_beans__green_yield,broad_beans_yield,cabbages_yield,carrots_and_turnips_yield,cauliflowers_and_broccoli_yield,cereals_n_e_c__yield,cereal_yield,cherries_yield,chestnut_yield,chickpeas_yield,chillies_and_peppers__green__capsicum_spp__and_pimenta_spp__yield,citrus_fruit_yield,cucumbers_and_gherkins_yield,currants_yield,eggplants_yield,fibre_crops__fibre_equivalent_yield,figs_yield,flax__raw_or_retted_yield,fruit_yield,garlic_yield,grapefruit_yield,grapes_yield,groundnut_yield,hazelnuts_yield,hempseed_yield,hop_cones_yield,kiwi_yield,leeks_yield,lemons_and_limes_yield,lettuce_yield,linseed_yield,locust_beans__carobs__yield,lupins_yield,maize_yield,melon_yield,millet_yield,oats_yield,oilcrops__cake_equivalent_yield,oilcrops__oil_equivalent_yield,olives_yield,onions_and_shallots__green_yield,onions_yield,orange_yield,other_berries_and_fruits_of_the_genus_vaccinium_n_e_c__yield,other_fruits__n_e_c__yield,other_nuts__excluding_wild_edible_nuts_and_groundnuts__in_shell__n_e_c__yield,other_pome_fruits_yield,other_pulses_n_e_c__yield,other_stone_fruits_yield,other_vegetables__fresh_n_e_c__yield,peaches_and_nectarines_yield,pears_yield,peas__green_yield,pineapples_yield,plums_yield,potato_yield,pulses_yield,pumpkins__squash_and_gourds_yield,quinces_yield,raspberries_yield,rice_yield,roots_and_tubers_yield,rye_yield,safflower_seed_yield,sour_cherries_yield,spinach_yield,strawberries_yield,sugarbeet_yield,sugarcane_yield,sugar_crops_yield,sunflower_yield,sweet_potatoes_yield,tangerines_yield,tea_yield,tobacco_yield,tomato_yield,treenuts_yield,triticale_yield,true_hemp__raw_or_retted_yield,vegetables_yield,walnuts_yield,watermelons_yield,wheat_yield,yams_yield
10422,Portugal,1961,0.4324,4.6667,8.296,NaN,NaN,32.190500,0.4106,0.1598,10.0,NaN,10.0,0.3657,16.6667,31.818200,NaN,NaN,0.7848,10.571400,2.0000,0.3717,2.9412,8.508100,NaN,NaN,NaN,0.9695,0.9000,0.955720,3.1753,6.0,5.0000,4.7244,NaN,1.2500,0.2459,NaN,NaN,NaN,7.6923,20.0,0.2952,NaN,0.7925,1.2779,13.200000,1.7738,0.2422,13.9183,492.30328,NaN,NaN,19.555600,8.7333,NaN,3.32,0.7050,NaN,0.6250,2.5,15.002899,8.9907,9.090899,NaN,7.5000,16.503600,9.753500,0.2175,15.0,5.0,NaN,4.6781,9.592100,0.3995,NaN,3.1950,NaN,1.6500,36.5200,38.4615,36.920600,NaN,7.1429,7.7000,0.6400,2.5000,23.920000,1.2880,NaN,1.0000,16.479300,2.6923,5.5000,0.6515,7.8947
10423,Portugal,1962,0.4737,3.8667,6.840,NaN,NaN,28.977299,0.5362,0.1352,10.0,NaN,10.0,0.5276,16.6667,36.363598,NaN,NaN,0.8806,11.178599,2.0000,0.3086,2.9412,9.613999,NaN,NaN,NaN,0.9247,0.9367,0.809524,4.7495,6.0,7.4074,8.7125,NaN,1.2500,0.2632,NaN,NaN,NaN,10.0000,21.0,0.2564,NaN,0.8070,1.1751,13.578899,1.7260,0.3603,12.8708,197.96260,NaN,NaN,18.600000,10.0645,NaN,3.36,0.7080,NaN,0.6875,2.5,13.275600,7.2000,9.545500,NaN,7.5000,7.478300,8.779900,0.2114,15.0,5.0,NaN,4.7346,8.673099,0.5546,NaN,2.8571,NaN,1.6579,32.6087,38.4615,34.722200,NaN,7.1429,6.1500,0.5556,2.5000,31.743198,1.3451,NaN,1.1316,16.337100,2.5000,5.5000,0.8857,7.8947
10424,Portugal,1963,0.3333,5.1111,5.660,NaN,NaN,30.108700,0.4852,0.1412,10.0,NaN,10.0,0.5329,17.0213,30.000000,NaN,NaN,0.8286,10.551700,1.9394,0.3740,2.9412,6.679400,NaN,NaN,NaN,0.8460,1.0767,0.781481,4.2785,6.0,7.4074,7.2939,NaN,1.4000,0.2655,NaN,NaN,NaN,7.6923,20.0,0.2593,NaN,0.8017,1.0729,13.636399,1.7241,0.3342,15.8319,461.70160,NaN,NaN,21.199999,6.8667,NaN,3.40,0.7125,NaN,0.6875,2.5,16.000000,8.8286,11.599999,NaN,7.8125,12.160000,10.723100,0.2283,15.0,5.0,NaN,4.5518,10.496300,0.6775,NaN,2.8571,NaN,1.9250,36.0000,37.5000,36.486500,NaN,7.3333,4.2778,0.6000,2.4889,33.939000,1.1390,NaN,1.0000,18.670500,2.3214,5.6667,0.8002,7.8947
10425,Portugal,1964,0.3611,5.0000,4.430,NaN,NaN,31.844700,0.4121,0.1510,10.0,NaN,10.0,0.4711,16.9811,30.555600,NaN,NaN,0.8143,11.965500,2.1951,0.3241,2.9412,8.679999,NaN,NaN,NaN,0.9794,1.2200,0.778598,4.4961,6.0,7.4074,7.4960,NaN,1.4545,0.2410,NaN,NaN,NaN,7.6923,20.0,0.3395,NaN,0.8000,1.2027,13.318200,1.7256,0.2790,13.9221,162.52130,NaN,NaN,18.975000,9.3125,NaN,3.44,0.7170,NaN,0.7500,2.5,17.002499,5.0000,10.666699,NaN,7.8125,9.458300,10.468699,0.2137,15.0,5.0,NaN,4.7991,10.306100,0.5358,NaN,2.8571,NaN,2.5750,32.6087,37.5000,34.285698,NaN,8.0000,4.2105,0.6000,2.0000,33.782600,1.3568,NaN,1.3072,19.978899,2.3214,5.4839,0.6887,8.0952
10426,Portugal,1965,0.3684,5.3333,7.760,NaN,NaN,32.075500,0.5735,0.1243,10.0,NaN,10.0,0.3780,16.9643,30.952398,NaN,NaN,0.8557,12.599999,1.0682,0.2069,2.9412,9.095400,NaN,NaN,NaN,0.9378,1.0667,0.836237,4.7629,6.0,7.4074,8.0760,NaN,1.6667,0.2609,NaN,NaN,NaN,8.7500,20.0,0.3659,NaN,0.7000,0.9483,13.461499,1.7204,0.3649,16.6310,320.25860,NaN,NaN,19.047600,9.6250,NaN,3.48,0.7215,NaN,0.6875,2.5,16.998999,7.4082,12.400000,NaN,7.7651,8.916699,8.778100,0.1747,15.0,5.0,NaN,3.8688,8.728600,0.6610,NaN,2.8571,NaN,2.5000,39.0000,37.5000,38.513500,NaN,8.1250,5.7023,0.6000,2.1765,33.142900,0.8003,NaN,1.1913,21.141200,2.3214,5.6452,0.9750,8.0000

In [46]:
# Write to .csv
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/crop_yield_cleaned.csv"
df_cleaned.to_csv(file_name, sep=',', encoding='utf-8')

In [ ]:
# Convert from wide to long format
melted_df = df_cleaned.melt(id_vars=['country', 'year'], var_name='crop', value_name='yield')

In [ ]:
melted_df = melted_df.dropna(),
# melted_df['crop'].unique()

In [ ]:
melted_df['crop'] = melted_df['crop'].str.replace('_yield', '')

In [ ]:
# Write to .csv,
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_crop_data_long.csv"
melted_df.to_csv(file_name, sep=',', encoding='utf-8')

In [ ]:
top_20_crops = melted_df.sort_values(['year', 'yield'], ascending=[True, False]),
                        .groupby('year'),
                        .head(20),
                        .sort_values('year')

In [ ]:
# Write to .csv
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_top_20_crops_by_year.csv"
top_20_crops.to_csv(file_name, sep=',', encoding='utf-8')

In [ ]:
# Make a list of unique crops,
sorted_unique_values = sorted(melted_df['crop'].unique()),
unique_crops_df = pd.DataFrame(sorted_unique_values, columns=['crop'])

In [ ]:
# Add a cropID column

In [ ]:
# Write to .csv",
today = datetime.now().strftime("%Y%m%d")
file_name = "/Users/eleshuk/Library/CloudStorage/GoogleDrive-eleshuk@gmail.com/.shortcut-targets-by-id/1XNkQR60z1T7WELqvqkvZchRrVWQpCzvs/data_science_project/Project Template/data/processed/"+today+"_unique_crops.csv,
unique_crops_df.to_csv(file_name, sep=',', encoding='utf-8')